Update keycloak v12 theme v2
europeana/keycloak-theme pull request #25
Opened 2021-09-29 15:39 UTC by LeoniePeters

2021-09-30 09:13 UTC, rwd requested changes

2021-09-30 09:13 UTC, rwd commented on deploy/cloud-foundry/manifest.yml
> +  image: europeana.v2/keycloak-theme:latest
This does not need to be changed. If we build and push a new version, it will still be tagged `europeana.v2/keycloak-theme:latest`. Revert this change.

2021-09-30 09:13 UTC, rwd commented on docker-compose.yml
> +        target: /opt/jboss/keycloak/themes/europeana.v2
Why change the target path inside the container? Revert this change.

2021-09-30 09:13 UTC, rwd commented on keycloak/europeana-realm.json
> +  "loginTheme": "europeana.v2",
There is no need to rename the theme. Change it back to `europeana`

2021-10-04 09:48 UTC, lbiedinger commented on keycloak/europeana-realm.json
>    ],
Why are these removed?

2021-10-04 10:06 UTC, LeoniePeters commented on keycloak/europeana-realm.json
>    ],
I don't know. This is an export of the realm I configured in the KeyCloak admin console. I didn't do anything with the locales there as far as I can remember. Shall we try and put them back in?

2021-10-04 10:06 UTC, LeoniePeters commented on keycloak/europeana-realm.json
>    ],
I don't know. This is an export of the realm I configured in the KeyCloak admin console. I didn't do anything with the locales there as far as I can remember. Shall we try and put them back in?

2021-10-04 11:18 UTC, lbiedinger commented on keycloak/europeana-realm.json
>    ],
yes, let's put it back, otherwise we can't access the language using `&ui_locales=xx`, it just goes back to the browser language for any of the ones that have been removed with the changes here.

2021-10-05 13:38 UTC, lbiedinger approved these changes

2021-10-08 09:10 UTC, merged