Feat/xx 59 account profile edit
europeana/keycloak-theme pull request #7
Opened 2020-08-24 12:29 UTC by annachristaki

2020-08-24 14:30 UTC, rwd requested changes

2020-08-24 14:30 UTC, rwd commented on keycloak/europeana-realm.json
> +  "editUsernameAllowed": true,
Let's make the europeana theme the default for this realm, with:
```diff
diff --git a/keycloak/europeana-realm.json b/keycloak/europeana-realm.json
index 6b1353c..221a221 100644
--- a/keycloak/europeana-realm.json
+++ b/keycloak/europeana-realm.json
@@ -600,6 +600,7 @@
     "from": "admin@keycloak"
   },
   "loginTheme": "europeana",
+  "accountTheme": "europeana",
   "eventsEnabled": false,
   "eventsListeners": [
     "jboss-logging"
```

2020-08-25 06:13 UTC, annachristaki commented on keycloak/europeana-realm.json
> +  "editUsernameAllowed": true,
You are right, forgot to include that:+1:

2020-08-25 07:15 UTC, rwd approved these changes

2020-08-25 12:56 UTC, mirjamverloop requested changes

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/password.ftl
> +                    <button type="submit" class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonLargeClass!}" name="submitAction" value="Save">${msg("changePass
Accoding to the design, the font-weight of the text should be 600. I also think that is consistent with buttons used elsewhere.

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/template.ftl
> +    <link rel="icon" href="${url.resourcesPath}/favicon.ico" />
In the theme/login/template.ftl this path has been updated to `<link rel="icon" href="${url.resourcesPath}/img/favicon.ico" />`. Should it be updated here too?

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/theme.properties
> +kcContentClass=col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3
No need to add `col-lg-6 col-lg-offset-3`

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/theme.properties
> +kcLocaleClass=col-xs-12 col-sm-1
`col-xs-12` doesn't exist, `col-12` does.

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/theme.properties
> +kcFormAreaClass=col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2
I don't think there is a need for adding `col-lg-8 col-lg-offset-2`.

2020-08-25 12:56 UTC, mirjamverloop commented on theme/account/theme.properties
> +kcFormSocialAccountContentClass=col-xs-12 col-sm-6
`col-xs-12 ` doesn't exist, `col-12` does.

2020-08-26 10:35 UTC, annachristaki commented on theme/account/theme.properties
> +kcLabelWrapperClass=col-xs-12 col-sm-12 col-md-12 col-lg-12
This file was copied over from the original Keycloak theme that served as the base for the custom europeana theme. The styles in theme.properties were predefined and not created during theme customisation (and also not checked for errors/redundancies). Very few of them are still used in the updated ftl files so maybe it's worth to do a cleanup.

2020-08-26 11:02 UTC, annachristaki commented on theme/account/template.ftl
> +    <link rel="icon" href="${url.resourcesPath}/favicon.ico" />
this is not used, I will remove it, favicon is set further down

2020-08-27 10:19 UTC, mirjamverloop approved these changes

2020-08-27 10:19 UTC, merged